---
title: "Application of Principal Component Analysis and Segmentation on Sentinel-1 and Sentinel-2 imagery for Habitat Mapping"
description: "Assessment created for Environmental Intelligence CDT, University of Exeter"
author: "Brianna Pickstone"
date: today
title-block-banner: true
bibliography: references.bib
format: 
  html: 
   theme: journal
   embed-resources: true
---

## Overview 

This workbook provides both an overview of the importance of habitat mapping, as well as providing an example, using the R programming language, for implementing both Principal Component Analysis and Segmentation to Earth Observation (EO) data.

The workbook will first provide an introduction to habitat mapping and the significance of Principal Component Analysis and Segmentation. It will then provide an overview of the dataset that will be used, followed by how to download Sentinel-1 and Sentinel-2 imagery. It will then go through the workflow to apply PCA and segmentation to the EO data. It will finally analyse the outputs of these, and final remarks will be made in the discussion.

## Introduction

-   Highlight the role of habitat mapping in:

    -   Understanding species distributions and biodiversity patterns

    -   Identifying critical habitat areas for conservation prioritization

    -   Monitoring habitat changes and ecosystem dynamics over time

    -   Informing land use planning and natural resource management decisions

-   Emphasize the need for accurate, reliable, and spatially explicit habitat maps to support evidence-based conservation actions and sustainable development initiatives.

**. Role of PCA and Segmentation in Habitat Mapping**

-   Principal Component Analysis (PCA) and image segmentation are two widely used techniques in remote sensing and spatial analysis that hold promise for enhancing habitat mapping.

-   PCA allows for the reduction of high-dimensional spectral data into a smaller set of uncorrelated variables (principal components), facilitating the identification of key spectral patterns and features associated with different habitat types.

-   Image segmentation partitions an image into meaningful segments or regions based on spectral, spatial, or contextual similarities, enabling the delineation of homogeneous habitat units and the extraction of spatially explicit information.

-   By integrating PCA and segmentation, researchers can combine the benefits of dimensionality reduction and spatial aggregation to improve the accuracy, interpretability, and efficiency of habitat mapping models.

QUestions

-   a need for spatially extensiv

-   

-   **. Objectives of the Report**

    -   The primary objective of this report is to explore the use of PCA and segmentation techniques for habitat mapping and ecological analysis.

    -   Specific objectives include:

        -   Investigating the applicability of PCA for dimensionality reduction of spectral data and identification of important spectral patterns associated with different habitat types.

        -   Evaluating the effectiveness of image segmentation methods for delineating habitat units and capturing spatial heterogeneity within the landscape.

        -   Assessing the synergistic effects of integrating PCA and segmentation in habitat mapping models and their implications for ecological research and conservation planning.e and rapidly updatable biodiversity info

-   classified data must be as readily useful to ecologists as possible (useful on the ground) - or other stakeholders

-   need for rapid habitat monitoring at a range of scales

-   discover a reliable workflow for converting remote sensing data into derived habitat maps that are of a standard for ecologists to take out into the field

-   what are the key features of each habitat type that allow the machine learning algorithm to differntiate it over other habitat types? - is it spectral? topographic?

-   What can actually be remotely sense?

-   

## Methodology 

## Results 

## Discussion

## Conclusion

```{r}
1 + 1
```
